CC		= g++
CFLAGS		= -g -c -Wall -g
LDFLAGS		= 
SOURCES		= client.cpp  tcpConnections/tcpstream.cpp tcpConnections/tcpconnector.cpp \
				
INCLUDES	= -I.
OBJECTS		= $(SOURCES:.cpp=.o)
TARGET		= client

all: $(SOURCES) $(TARGET)

$(TARGET): $(OBJECTS) 
	$(CC) $(LDFLAGS) $(OBJECTS) -o $@

.cpp.o:
	$(CC) $(CFLAGS) $(INCLUDES) $< -o $@

clean:
	rm -rf $(OBJECTS) $(TARGET)

